apiVersion: kni.akraino.org/v1alpha1
kind: SiteConfig
metadata:
  name: notImportantHere
config:
  OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: "quay.io/openshift-release-dev/ocp-release-nightly@sha256:206fd17bcc13e67804a1862b7cc656186e64a9c9ab941881e1d26832510c3e5e"
